# -*- coding: utf-8 -*-
"""MNIST_CNN_Tensorflow (1).ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g7PTrtunlkZMtexTL90eRmism6vUr7ZG
"""

from google.colab import files
uploaded = files.upload()

!jupyter nbconvert --to script "MNIST_CNN_Tensorflow (1).ipynb" --output "app.py"
!mv "MNIST_CNN_Tensorflow (1).txt" app.py

!ls -l app.py

from google.colab import files
files.download("MNIST_CNN_Tensorflow (1).py")

# Clean up any old files
!rm -f app.py app.py.txt

# 1. Force conversion with clean name and known output
!jupyter nbconvert --to script "MNIST_CNN_Tensorflow (1).ipynb" --output app

# 2. Rename .txt to .py (nbconvert appends .txt anyway)
!mv app.txt app.py

# 3. Check if conversion worked
!ls -lh app.py

# === STEP 1: Streamlit-ize app.py ===
with open("app.py", "r") as f:
    lines = f.readlines()

streamlit_header = [
    "import streamlit as st\n",
    "import matplotlib.pyplot as plt\n",
    "st.set_page_config(page_title='MNIST CNN', layout='wide')\n",
    "st.title('🧠 MNIST CNN Classifier using TensorFlow')\n\n"
]

new_lines = []
for line in lines:
    if "print(" in line:
        line = line.replace("print(", "st.write(")
    if "plt.show()" in line:
        line = "st.pyplot(plt)\n"
    new_lines.append(line)

with open("app.py", "w") as f:
    f.writelines(streamlit_header + new_lines)

print("✅ app.py updated for Streamlit")

# === STEP 2: Create requirements.txt ===
with open("requirements.txt", "w") as f:
    f.write("streamlit\n")
    f.write("tensorflow\n")
    f.write("matplotlib\n")

print("✅ requirements.txt created")

# === STEP 3: Create README.md ===
readme_content = (
    "# MNIST CNN with TensorFlow + Streamlit\n\n"
    "This Streamlit app trains and evaluates a CNN on the MNIST handwritten digits dataset using TensorFlow.\n\n"
    "## 🔗 Live App\n"
    "Once deployed, your app will be at: https://YOUR_USERNAME.streamlit.app/\n\n"
    "## 🚀 Features\n"
    "- CNN model built with TensorFlow\n"
    "- Runs in-browser with Streamlit\n"
    "- Output metrics and digit classification\n\n"
    "## ▶️ Run Locally\n"
    "```bash\n"
    "pip install -r requirements.txt\n"
    "streamlit run app.py\n"
    "```\n"
)

with open("README.md", "w") as f:
    f.write(readme_content)

print("✅ README.md created")